spring:

  datasource:
    url: jdbc:mysql://localhost:3306/git
    username: root
    password: 13850179569
    driver-class-name: com.mysql.cj.jdbc.Driver
  spring:
    security:
      enabled: false


mybatis:
  mapper-locations: classpath:mapper/*.xml
server:
  port: 8081

